### PR TITLE
Squash PR 129 : Make disco_bake listamis also filter by state and hos…

### PR DESCRIPTION
**Pull request by IlyaSukhanov**
…tclass

Signed-off-by: Pratap Chand <pchand@amplify.com>

### CODE REVIEW

**Comment by pchand-amplify** [comment]
Like the hostclass option but not sure about the state. What are the use cases for using state?

**Comment by pchand-amplify** [comment]
Ok seems like there are a few fallouts in the old repo PR. Address them when you get a chance. @jconstance-amplify, you already have a +1 there so you should be good to go.

**Comment by pchand-amplify** [comment]
version bump

**Comment by jconstance-amplify** [comment]
I was running into some problems updating the names of the AMIs on the old branch, but I'll try to get this ready sometime this week.

**Pull request merged**
