### PR TITLE
to set a private ip we now use ip_address so update the README

### PR DESCRIPTION
**Pull request by bsuzukiamplify**

### CODE REVIEW

**Comment by jichen-amplify** [comment]
Besides bumping the version, 👍

**Comment by bwarfield-amplify** [comment]
👍 

Also I don't think this actually needs a version bump...

**Comment by IlyaSukhanov** [comment]
+1

**Comment by bsuzukiamplify** [comment]
Heh, apparently @jichen-amplify was right, the PR build job failed because I didn't update the version.  Probably a bit overzealous, but okay.

**Pull request merged**
