### PR TITLE
Squash PR 114: add tags for ELBs

### PR DESCRIPTION
**Pull request by IlyaSukhanov**

### CODE REVIEW

**Comment by aoskotsky-amplify** [comment]
@pchand-amplify @jconstance-amplify @IlyaSukhanov 

Can I merge this?

**Comment by pchand-amplify** [comment]
Can you elaborate on what tags are being attached to the ELB?

**Comment by aoskotsky-amplify** [comment]
The tags are:
- hostclass
- owner - the user that ran the asiaq command
- environment -  ci/staging/etc
- productline - from disco_aws.ini file

**Comment by pchand-amplify** [comment]
Is there a way to extract the productline tag from the running instance, instead of the ini file?

**Comment by jconstance-amplify** [comment]
@pchand-amplify @IlyaSukhanov @aoskotsky-amplify @jichen-amplify 

I'd also like to merge/combine this with #87, especially because it would make collecting/viewing metrics for Datadog easier.

Any arguments against that?

**Pull request closed without merging**
