### PR TITLE
Made no-destroy SSH command stop saving host keys.

### PR DESCRIPTION
**Pull request by bwarfield-amplify**
Modified the disco_bake output to include the necessary option to avoid saving the IP address and host key when connecting to a host baked with the --no-destroy option.

### CODE REVIEW

**Comment by pchand-amplify** [comment]
👍

**Comment by pchand-amplify** [comment]
build

**Comment by bwarfield-amplify** [comment]
build

**Comment by pchand-amplify** [comment]
Reason for closing?

**Comment by bwarfield-amplify** [comment]
It's super annoying to have a one-line PR turn into five commits of merges and version updates.

**Pull request closed without merging**
