### PR TITLE
Fix call to adduser in acfg1.py to work in centos5

### PR DESCRIPTION
**Pull request by msthippolyte-amplify**
The version of adduser in Centos 5 does not support the --system option, however it supports -r which does the same thing.  acfg1.py calls adduser with --system, causing it to break when baking mhcpreamp.  This change should allow acfg1.py to work on Centos 5 without any change in behavior in other versions.

### CODE REVIEW

**Comment by pchand-amplify** [comment]
Does this work on centos 6 and 7? and why didnt this break on the other centos 5 hostclass?

**Comment by sthippo** [comment]
I need to test it, which brings up a question.  How do I test asiaq changes locally?  I don't think it works to just bake it locally with my changes in ../asiaq, or does it?

**Comment by pchand-amplify** [comment]
Since this is a system call you just bake and see if it doesnt break anything during bake. make sure you have `--stage` set when you are baking so your changes doesnt get picked up by phase2 bakes.

**Comment by pchand-amplify** [comment]
build

**Comment by pchand-amplify** [comment]
👍

**Pull request merged**
