### PR TITLE
[WIP] Enable Metrics for ASG

### PR DESCRIPTION
**Pull request by IlyaSukhanov**
NOTE: Alarms still cannot be created as ASGs are named somewhat
randomly. So alarms will have to be aware of that and will need
to be updated any time ASG is changed. Cannot think of sensible
way to do that.

### CODE REVIEW

**Comment by johnamplify** [comment]
So if I'm understanding, this enables metrics for the ASG with its original name when it's provisioned, but if it ever updates, metrics would break?

**Comment by IlyaSukhanov** [comment]
Metrics wont break. IIRC, we don't update ASGs but re-create them so you'd get a new metric on update as well. But alarms will have been tied to old metric name which would no longer exist.

Furthermore, we create alarms with the VPC and since ASG name is dynamically generated later (at spinup) changes will have to be made to account for it.

**Comment by jconstance-amplify** [comment]
AFAIK, you should just need to add support to disco_alarms.py for the `AWS/AutoScaling` namespace. disco_alarms.py already provided the autoscaling group name as the dimension for the `AWS/EC2` namespace, so probably just need to do the same here. https://github.com/amplifylitco/asiaq/blob/master/disco_aws_automation/disco_alarm_config.py#L88

**Comment by jconstance-amplify** [comment]
ok to test

**Pull request closed without merging**
