### PR TITLE
Squash PR 67: Test-and-Deploy job: fail if integration tests fail

### PR DESCRIPTION
**Pull request by IlyaSukhanov**

### CODE REVIEW

**Comment by pchand-amplify** [comment]
Build

**Comment by bwarfield-amplify** [comment]
Any argument against merging this?

**Comment by jconstance-amplify** [comment]
I think there were still a few valid concerns here: https://github.com/amplifylitco/X_DEPRECATED_asiaq/pull/67

Mostly that instead of going off of the tag, returning a boolean would make more sense and be less likely to break with different tags being introduced.

**Comment by pchand-amplify** [comment]
Should we close this PR?

**Comment by jconstance-amplify** [comment]
I think there would still be value in having `disco_deploy.py` return a failure code. We should probably make a story for it though.

**Comment by aoskotsky-amplify** [comment]
Closing. Replaced by https://github.com/amplifylitco/asiaq/pull/194

**Pull request closed without merging**
