### PR TITLE
Squash PR 87: Add productline to autoscale group, which should add it…

### PR DESCRIPTION
**Pull request by IlyaSukhanov**
… to the instance

### CODE REVIEW

**Comment by aoskotsky-amplify** [comment]
Is this going to be merged?

**Comment by jconstance-amplify** [comment]
@pchand-amplify had some concerns.

**Comment by aoskotsky-amplify** [comment]
I think the issue was about how the product line will get set in staging/production. We can do something like this https://github.com/amplifylitco/asiaq_astro_config/pull/250/files#diff-0894c045e3d36015feff618fd2365857R193

**Comment by pchand-amplify** [comment]
This looks great but I still don't see the benefit of adding tags to an autoscaling group.

**Comment by jconstance-amplify** [comment]
Well, in actuality, it doesn't matter if we tag the autoscaling group or not. It was just thought that that was one way to add the tag to the instance at run time, rather than relying on /opt/wgen/etc/productline.

As far as I know, the productline tag for an instance is used solely to help construct a report of attributing cost to product lines. Ergo, if productline A spins up a bunch of instances from AMIs made by productline B, shouldn't productline A have the cost of the instances attributed to them? Assuming that is something we want, it seems like the easiest way to accomplish that is by having a productline option in disco_aws.ini and associating whatever that value is with the instances being spun up.

**Comment by pchand-amplify** [comment]
@jconstance-amplify : Well its not always true. Lets say for some reason the spin up job failed. If productline A notices and spins it up for B, should A be charged for bringing the service back? 

If we do take @aoskotsky-amplify solution then we will not be able to track who spun it up anyways.

**Comment by IlyaSukhanov** [comment]
Closing PR due to lack of interest.

**Pull request closed without merging**
