### PR TITLE
Fixed VPC peering update

### PR DESCRIPTION
**Pull request by kelibezhani**
When running `disco_vpc_ui.py update`, the code would attempt to create another VPC peering between two VPCs if peering direction in disco_vpc.ini is the opposite.

*Example:*
```
disco_vpc_ui.py peerings --list
pcx-7069e219   active   test-peering-1<->test-peering-2 10.254.124.0/22<->10.253.92.0/22
```
*Note: current VPC peering has as requester test-peering-1, and as accepter test-peering-2*

**disco_vpc.ini**
```
connection_12=test-peering-2:sandbox/intranet test-peering-1:sandbox/intranet
connection_13=test-peering-2:sandbox/maintenance test-peering-1:sandbox/intranet
```
*Note: configured VPC peering has as requester test-peering-2, and as accepter is test-peering-1*

### CODE REVIEW

**Comment by aoskotsky-amplify** [comment]
Can you test if this also works with wildcard syntax like 
`connection_12=*:sandbox/intranet test-peering-1:sandbox/intranet`

**Comment by kelibezhani** [comment]
> Can you test if this also works with wildcard syntax like
> connection_12=*:sandbox/intranet test-peering-1:sandbox/intranet

Running `disco_vpc-ui.py update --name test-peering-1` will try to establish VPC peering between this VPC and all other sandbox VPCs. I tried and I got the following error:
```
2017-05-02 09:53:52,541 disco_aws_automation.disco_aws_util ERROR EC2 Error response: An error occurred (PendingVpcPeeringConnectionLimitExceeded) when calling the CreateVpcPeeringConnection operation: Vpc peering connection request limit exceeded.
```

**Comment by kelibezhani** [comment]
Running `update` again worked.

**Comment by aoskotsky-amplify** [comment]
build

**Pull request merged**
