### PR TITLE
Fixed some spinup/sandbox gotchas.

### PR DESCRIPTION
**Pull request by bwarfield-amplify**
Added an explicit dependency on a recent botocore, since previously-installed virtualenvs will not have a good enough version for sandbox setup, and factored out some repeated code in the disco_aws command-line script in order to make it check for a stupid error in pipeline file construction.

### CODE REVIEW

**Comment by aoskotsky-amplify** [comment]
👍 version needs to be bumped

**Comment by bwarfield-amplify** [comment]
There is a version bump. 😛  (There's also a pep8 failure, which is why the PRB failed)

**Comment by bwarfield-amplify** [comment]
retest

**Comment by bwarfield-amplify** [comment]
build

**Pull request merged**
