### PR TITLE
Don't supply bogus Subnet when creating ELB in testing.

### PR DESCRIPTION
**Pull request by IlyaSukhanov**
We supply empty list anyway, this way moto does not try
to look up the bogus VPC. Ideally we'd create the subnet first,
but don't think that adds much to our tests.

### CODE REVIEW

**Comment by IlyaSukhanov** [comment]
build

**Comment by IlyaSukhanov** [comment]
build

**Comment by IlyaSukhanov** [comment]
build

**Comment by pchand-amplify** [comment]
build

**Comment by IlyaSukhanov** [comment]
build

**Comment by jichen-amplify** [comment]
👍

**Pull request merged**
