### PR TITLE
Rebooting the instance during spinup,

### PR DESCRIPTION
**Pull request by rdevineni-amplify**
so the parameter group is applied. This fixes all the performance issues we've been seeing in CI-txdb

### CODE REVIEW

**Comment by rdevineni-amplify** [comment]
@bvargheseamplify @pchand-amplify

**Comment by bvargheseamplify** [comment]
+1

**Comment by pchand-amplify** [comment]
Is this a requirement to apply changes in RDS?

**Comment by rdevineni-amplify** [comment]
Yes. When modifying the db instance, The custom parameter group can only be applied if a reboot happens. This is because most of our Custom Parameters are static which require reboot.

**Pull request merged**
