### PR TITLE
Long disk name metrics fix

### PR DESCRIPTION
**Pull request by pchand-amplify**
- Changed `df` output to be posix standard. This allows names like `/dev/mapper/VolGroup00-LogVol00` to be in a single line.<br>
 `df` : 
<pre>
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/mapper/VolGroup00-LogVol00
                      36533824   4690160  29957868  14% /
/dev/hda1               101086     16491     79376  18% /boot
tmpfs                  3833916         0   3833916   0% /dev/shm
/dev/xvdb             51606140    186512  48798188   1% /mnt/san-nfs
</pre>

 `df -P`:
<pre>
Filesystem         1024-blocks      Used Available Capacity Mounted on
/dev/mapper/VolGroup00-LogVol00  36533824   4690192  29957836      14% /
/dev/hda1               101086     16491     79376      18% /boot
tmpfs                  3833916         0   3833916       0% /dev/shm
/dev/xvdb             51606140    186512  48798188       1% /mnt/san-nfs
</pre>

### CODE REVIEW

**Comment by IlyaSukhanov** [comment]
+1

**Comment by aoskotsky-amplify** [comment]
👍

**Comment by IlyaSukhanov** [comment]
+2

**Comment by jichen-amplify** [comment]
👍

**Comment by aoskotsky-amplify** [comment]
+3

**Comment by jconstance-amplify** [comment]
+NaN

**Pull request merged**
