### PR TITLE
AS-461 Use ELB name rather than id for AWS/ELB alarm dimension

### PR DESCRIPTION
**Pull request by thayes-amplify**
Perhaps there's more to it than this, but I thought I would give it a shot.

### CODE REVIEW

**Comment by pchand-amplify** [comment]
Has this been tested?

**Comment by thayes-amplify** [comment]
@pchand-amplify Unit test has been updated to pass, but other than that no.  Thought I'd get an astronaut to look at this first since it's so small.
Not really sure how I would test it anyway to be honest.

**Comment by aoskotsky-amplify** [comment]
Has this been tested? I'm not sure if this will work since as far as AWS is concerned, the LoadBalancerName field is what we are calling ELB Id. The actual name is being kept in a tag that CloudWatch doesn't know about.

Also this might not be that useful for us anymore since user traffic isn't coming into the ELBs anymore after we switched away from F5.

**Comment by thayes-amplify** [comment]
No this hasn't been tested.  I have been OOO for a few weeks. Sounds like we can close this as not applicable anymore since switching away from F5 as per Alex's comment.

**Pull request closed without merging**
