### PR TITLE
Disable os specific user keys after enabling root

### PR DESCRIPTION
**Pull request by IlyaSukhanov**

### CODE REVIEW

**Comment by aoskotsky-amplify** [comment]
👍

**Comment by jconstance-amplify** [comment]
👍 , just needs a version bump

**Comment by pchand-amplify** [comment]
Has this been tested with centos 7 and ubuntu images?

**Comment by IlyaSukhanov** [comment]
Its being tested now. PR was sent first for sanity check reasons.

**Comment by pchand-amplify** [comment]
👍

**Pull request merged**
